name: Steam Publish

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore /p:EnableWindowsTargeting=true

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish /p:EnableWindowsTargeting=true

      - name: Package build as ZIP
        shell: pwsh
        run: Compress-Archive -Path publish\* -DestinationPath build.zip

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.sha }}
          path: build.zip

      - name: Get version
        id: package_version
        uses: KageKirin/get-csproj-version@v1.0.0
        with:
          file: VRCFaceTracking/VRCFaceTracking.csproj
          xpath: //PropertyGroup/AssemblyVersion
          regex: '^(?<major>0|[1-9]\d*)\.(?<minor>0|[1-9]\d*)\.(?<patch>0|[1-9]\d*)\.(?<build>0|[1-9]\d*)$'

      - uses: wilg/steam-deploy@steam-fix-windows
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          configVdf: ${{ secrets.STEAM_CONFIG_VDF}}
          appId: 3329480
          buildDescription: ${{ steps.package_version.outputs.version }}
          depot1Path: publish
          releaseBranch: development
